pdns-recursor: disable parallel jobs
Building with multiple jobs causes strange compilation errors:
mips-openwrt-linux-musl-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[5]: *** [Makefile:1465: lua-recursor4.o] Error 1
make[5]: *** Waiting for unfinished jobs....

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>