python-cryptography:  build only for 64-bit arches
The build system is picking up packages from the host, resulting in
errors when building for a 32-bit target using a 64-bit host.  I
couldn't figure out a way to make it work, so I'm drooping 32-bit
support instead.

  cargo:warning=cc1: note: someone does not honour COPTS correctly, passed 2 times
  cargo:warning=In file included from /usr/include/python3.14/Python.h:64,
  cargo:warning=                 from ./build_dir/target-arm_cortex-a9+neon-fp16_musl_eabi/pypi/cryptography-46.0.7/target/armv7-unknown-linux-musleabihf/release/build/cryptography-cffi-803330876d6e3e95/out/_openssl.c:57:
  cargo:warning=/usr/include/python3.14/pyport.h:429:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  cargo:warning=  429 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  cargo:warning=      |  ^~~~~

  --- stderr

  error occurred in cc-rs: command did not execute successfully (status code exit status: 1): LC_ALL="C" "arm-openwrt-linux-muslgnueabi-gcc" "-Os" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-mfpu=vfpv3-d16" "-mfloat-abi=hard" "-I" "./staging_dir/target-arm_cortex-a9+neon-fp16_musl_eabi/usr/include" "-I" "/usr/include/python3.14" "-DPy_LIMITED_API=0x030800f0" "-mcpu=cortex-a9" "-mfpu=neon-fp16" "-mfp16-format=ieee" "-funsafe-math-optimizations" "-O2" "-pipe" "-fno-plt" "-fhonour-copts" "-mfloat-abi=hard" "-fmacro-prefix-map=./build_dir/target-arm_cortex-a9+neon-fp16_musl_eabi/pypi/cryptography-46.0.7=cryptography-46.0.7" "-Wl,-z,max-page-size=4096" "-Wformat" "-Werror=format-security" "-fstack-protector" "-D_FORTIFY_SOURCE=1" "-Wl,-z,now" "-Wl,-z,relro" "-mcpu=cortex-a9" "-mfpu=neon-fp16" "-mfp16-format=ieee" "-funsafe-math-optimizations" "-O2" "-pipe" "-fno-plt" "-fhonour-copts" "-mfloat-abi=hard" "-fmacro-prefix-map=./build_dir/target-arm_cortex-a9+neon-fp16_musl_eabi/pypi/cryptography-46.0.7=cryptography-46.0.7" "-Wl,-z,max-page-size=4096" "-Wformat" "-Werror=format-security" "-fstack-protector" "-D_FORTIFY_SOURCE=1" "-Wl,-z,now" "-Wl,-z,relro" "-o" "./build_dir/target-arm_cortex-a9+neon-fp16_musl_eabi/pypi/cryptography-46.0.7/target/armv7-unknown-linux-musleabihf/release/build/cryptography-cffi-803330876d6e3e95/out/1fca3d716cd45828-_openssl.o" "-c" "./build_dir/target-arm_cortex-a9+neon-fp16_musl_eabi/pypi/cryptography-46.0.7/target/armv7-unknown-linux-musleabihf/release/build/cryptography-cffi-803330876d6e3e95/out/_openssl.c"

warning: build failed, waiting for other jobs to finish...
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO CARGO_ENCODED_RUSTFLAGS="-Ctarget-feature=-crt-static\u{1f}-lssp_nonshared\u{1f}-Clink-arg=-fuse-ld=bfd\u{1f}-C\u{1f}target-feature=-crt-static" PYO3_BUILD_EXTENSION_MODULE="1" PYO3_CONFIG_FILE="./build_dir/target-arm_cortex-a9+neon-fp16_musl_eabi/pypi/cryptography-46.0.7/target/maturin/pyo3-config-armv7-unknown-linux-musleabihf-3.14.txt" "cargo" "rustc" "--profile" "release" "--target" "armv7-unknown-linux-musleabihf" "--message-format" "json-render-diagnostics" "--locked" "--manifest-path" "./build_dir/target-arm_cortex-a9+neon-fp16_musl_eabi/pypi/cryptography-46.0.7/src/rust/Cargo.toml" "--lib"`
Error: command ['maturin', 'pep517', 'build-wheel', '-i', './staging_dir/hostpkg/bin/python3.14', '--compatibility', 'off'] returned non-zero exit status 1

ERROR Backend subprocess exited when trying to invoke build_wheel

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>