python-cryptography: build only for 64-bit arches
The hostpkg includes are used, causing this failure if the target is
32-bits.

warning: cryptography-cffi@0.1.0: ./staging_dir/hostpkg/include/python3.13/pyport.h:399:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
warning: cryptography-cffi@0.1.0:   399 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
warning: cryptography-cffi@0.1.0:       |  ^~~~~

While a way to properly pass the target paths is not found, only build
it for 64-bit arches.

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>