python-gevent: mark BROKEN
Compiling src/gevent/resolver/cares.pyx because it changed.
[1/1] Cythonizing src/gevent/resolver/cares.pyx
performance hint: src/gevent/libev/corecext.pyx:1357:0: Exception check on '_syserr_cb' will always require the GIL to be acquired.
Possible solutions:
        1. Declare '_syserr_cb' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
        2. Use an 'int' return type on '_syserr_cb' to allow an error code to be returned.

Error compiling Cython file:
------------------------------------------------------------
...
cdef tuple integer_types

if sys.version_info[0] >= 3:
    integer_types = int,
else:
    integer_types = (int, long)
                          ^
------------------------------------------------------------

src/gevent/libev/corecext.pyx:69:26: undeclared name not builtin: long
Compiling src/gevent/libev/corecext.pyx because it changed.
[1/1] Cythonizing src/gevent/libev/corecext.pyx
Traceback (most recent call last):
  File "./staging_dir/hostpkg/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
    ~~~~^^
  File "./staging_dir/hostpkg/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "./staging_dir/hostpkg/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
    return hook(config_settings)
  File "./staging_dir/hostpkg/lib/python3.13/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./staging_dir/hostpkg/lib/python3.13/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
    self.run_setup()
    ~~~~~~~~~~~~~~^^
  File "./staging_dir/hostpkg/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
    exec(code, locals())
    ~~~~^^^^^^^^^^^^^^^^
  File "<string>", line 54, in <module>
  File "./build_dir/target-aarch64_cortex-a53_musl/pypi/gevent-23.9.1/_setuputils.py", line 249, in cythonize1
    new_ext = cythonize(
              ~~~~~~~~~^
        [ext],
        ^^^^^^
    ...<46 lines>...
        # cache="build/cycache",
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )[0]
    ^
  File "./staging_dir/hostpkg/lib/python3.13/site-packages/Cython/Build/Dependencies.py", line 1159, in cythonize
    cythonize_one(*args)
    ~~~~~~~~~~~~~^^^^^^^
  File "./staging_dir/hostpkg/lib/python3.13/site-packages/Cython/Build/Dependencies.py", line 1303, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: src/gevent/libev/corecext.pyx

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel

Signed-off-by: Eneas U de Queiroz <cotequeiroz@gmail.com>